### PR TITLE
Project Rename: Earthquake --> Namazu 

### LINKED ISSUE #141: Project Rename: Earthquake --> Namazu
We decided to rename "Earthquake" to "Namazu".

Namazu (鯰) means a catfish in Japanese: https://en.wiktionary.org/wiki/%E9%AF%B0#Japanese

Plan:
 * github repository: `osrg/namazu`
 * executable name: `nmz` (`namazu` has been already taken by http://www.namazu.org/  (https://packages.debian.org/jessie/namazu2))
  * installation: `go get github.com/osrg/namazu/nmz`
 * twitter: `NamazuTest`

ETA: by the end of this April

### PR DESCRIPTION
**Pull request by AkihiroSuda**
* github repository: `osrg/earthquake` --> `osrg/namazu`
* executable name: `earthquake` --> `nmz` (`go get github.com/namazu/nmz`)
* twitter :`@NamazuFuzzTest`
* environmental vars: `EQ_*` --> `NMZ_*`
* extra changes: 
 * `nmz container` argument change: `-eq-config` --> `-nmz-autopilot`
 * `nmz inspectors proc` argument change: `-root-pid` --> `-pid`
 
Close #141 

TODO:
 * add logo
 * test them all carefully

- - - -
PTAL @mitake 
If we want to rename something else, we should do it at this time.

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
CI failed because there is no `github.com/osrg/namazu` yet. Locally build passes.

**Comment by mitake** [comment]
thanks a lot, I'll look at it ASAP

**Comment by mitake** [comment]
Looks good, thanks a lot!

**Comment by AkihiroSuda** [comment]
`inspector/ethernet` test fails consistently:
```
[NMZ-DBG] 11:44:44.52: Registering a signal class "NopEvent" (at signal.go:48) 
[NMZ-DBG] 11:44:44.52: Registering a signal class "PacketEvent" (at signal.go:48) 
[NMZ-DBG] 11:44:44.52: Registering a signal class "LogEvent" (at signal.go:48) 
[NMZ-DBG] 11:44:44.52: Registering a signal class "FilesystemEvent" (at signal.go:48) 
[NMZ-DBG] 11:44:44.52: Registering a signal class "ProcSetEvent" (at signal.go:48) 
[NMZ-DBG] 11:44:44.52: Registering a signal class "CFunctionEvent" (at signal.go:48) 
[NMZ-DBG] 11:44:44.52: Registering a signal class "JavaFunctionEvent" (at signal.go:48) 
[NMZ-DBG] 11:44:44.52: Registering a signal class "NopAction" (at signal.go:48) 
[NMZ-DBG] 11:44:44.52: Registering a signal class "EventAcceptanceAction" (at signal.go:48) 
[NMZ-DBG] 11:44:44.52: Registering a signal class "ShellAction" (at signal.go:48) 
[NMZ-DBG] 11:44:44.52: Registering a signal class "PacketFaultAction" (at signal.go:48) 
[NMZ-DBG] 11:44:44.52: Registering a signal class "FilesystemFaultAction" (at signal.go:48) 
[NMZ-DBG] 11:44:44.52: Registering a signal class "ProcSetSchedAction" (at signal.go:48) 
=== RUN   TestHookSwitchInspector_10
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x80 addr=0x0 pc=0x41285b]

goroutine 24 [running]:
runtime.throw(0xb42e00, 0x2a)
	/home/suda/go/src/runtime/panic.go:530 +0x90 fp=0xc82119ea00 sp=0xc82119e9e8
runtime.sigpanic()
	/home/suda/go/src/runtime/sigpanic_unix.go:12 +0x5a fp=0xc82119ea50 sp=0xc82119ea00
runtime.mallocgc(0x20, 0x89df40, 0xc800000001, 0x437906)
	/home/suda/go/src/runtime/malloc.go:648 +0x8ab fp=0xc82119eb28 sp=0xc82119ea50
runtime.newarray(0x89df40, 0x1a, 0xc82119ebd0)
	/home/suda/go/src/runtime/malloc.go:798 +0xc9 fp=0xc82119eb68 sp=0xc82119eb28
runtime.makeslice(0x889380, 0x1a, 0x1a, 0x0, 0x0, 0x0)
	/home/suda/go/src/runtime/slice.go:32 +0x165 fp=0xc82119ebb8 sp=0xc82119eb68
runtime.gobytes(0xc821135e40, 0x1a, 0x0, 0x0, 0x0)
	/home/suda/go/src/runtime/string.go:331 +0x92 fp=0xc82119ec08 sp=0xc82119ebb8
github.com/vaughan0/go-zmq._Cfunc_GoBytes(0xc821135e40, 0x1a, 0x0, 0x0, 0x0)
	??:0 +0x3c fp=0xc82119ec38 sp=0xc82119ec08
github.com/vaughan0/go-zmq.fromMsg(0xc821135e30, 0x0, 0x0, 0x0)
	/home/suda/gopath/src/github.com/vaughan0/go-zmq/zmq.go:311 +0xca fp=0xc82119eca0 sp=0xc82119ec38
github.com/vaughan0/go-zmq.(*Socket).RecvPart(0xc821135d70, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/suda/gopath/src/github.com/vaughan0/go-zmq/zmq.go:244 +0x16d fp=0xc82119ecf0 sp=0xc82119eca0
github.com/vaughan0/go-zmq.(*Socket).Recv(0xc821135d70, 0xc8211881a0, 0x1, 0x1, 0x0, 0x0)
	/home/suda/gopath/src/github.com/vaughan0/go-zmq/zmq.go:255 +0xb3 fp=0xc82119ed58 sp=0xc82119ecf0
github.com/vaughan0/go-zmq.(*Channels).processSockets(0xc8211a4060)
	/home/suda/gopath/src/github.com/vaughan0/go-zmq/channels.go:153 +0xc02 fp=0xc82119efa8 sp=0xc82119ed58
runtime.goexit()
	/home/suda/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc82119efb0 sp=0xc82119efa8
created by github.com/vaughan0/go-zmq.(*Socket).ChannelsBuffer
	/home/suda/gopath/src/github.com/vaughan0/go-zmq/channels.go:38 +0x2d1

goroutine 1 [chan receive]:
testing.RunTests(0xb91d70, 0xfaa8e0, 0x1, 0x1, 0xc821187d01)
	/home/suda/go/src/testing/testing.go:583 +0x8d2
testing.(*M).Run(0xc821187ee8, 0xb91c98)
	/home/suda/go/src/testing/testing.go:515 +0x81
_/home/suda/WORK/namazu/nmz/inspector/ethernet.TestMain(0xc821187ee8)
	/home/suda/WORK/namazu/nmz/inspector/ethernet/ethernet_test.go:42 +0x1b9
main.main()
	_/home/suda/WORK/namazu/nmz/inspector/ethernet/_test/_testmain.go:52 +0x114

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/home/suda/go/src/runtime/asm_amd64.s:1998 +0x1

goroutine 5 [semacquire]:
sync.runtime_Syncsemacquire(0xc82001af90)
	/home/suda/go/src/runtime/sema.go:241 +0x201
sync.(*Cond).Wait(0xc82001af80)
	/home/suda/go/src/sync/cond.go:63 +0x9b
github.com/cihub/seelog.(*asyncLoopLogger).processItem(0xc8200ac240, 0x0)
	/home/suda/gopath/src/github.com/cihub/seelog/behavior_asynclooplogger.go:50 +0xee
github.com/cihub/seelog.(*asyncLoopLogger).processQueue(0xc8200ac240)
	/home/suda/gopath/src/github.com/cihub/seelog/behavior_asynclooplogger.go:63 +0x40
created by github.com/cihub/seelog.NewAsyncLoopLogger
	/home/suda/gopath/src/github.com/cihub/seelog/behavior_asynclooplogger.go:40 +0x91

goroutine 6 [semacquire]:
sync.runtime_Syncsemacquire(0xc82001b110)
	/home/suda/go/src/runtime/sema.go:241 +0x201
sync.(*Cond).Wait(0xc82001b100)
	/home/suda/go/src/sync/cond.go:63 +0x9b
github.com/cihub/seelog.(*asyncLoopLogger).processItem(0xc8200ac360, 0x0)
	/home/suda/gopath/src/github.com/cihub/seelog/behavior_asynclooplogger.go:50 +0xee
github.com/cihub/seelog.(*asyncLoopLogger).processQueue(0xc8200ac360)
	/home/suda/gopath/src/github.com/cihub/seelog/behavior_asynclooplogger.go:63 +0x40
created by github.com/cihub/seelog.NewAsyncLoopLogger
	/home/suda/gopath/src/github.com/cihub/seelog/behavior_asynclooplogger.go:40 +0x91

goroutine 18 [select]:
github.com/osrg/namazu/nmz/endpoint/local.(*LocalEndpoint).eventRoutine(0xfc8540)
	/home/suda/gopath/src/github.com/osrg/namazu/nmz/endpoint/local/localendpoint.go:44 +0x3c7
created by github.com/osrg/namazu/nmz/endpoint/local.(*LocalEndpoint).Start
	/home/suda/gopath/src/github.com/osrg/namazu/nmz/endpoint/local/localendpoint.go:100 +0x14e

goroutine 19 [select]:
github.com/osrg/namazu/nmz/endpoint/local.(*LocalEndpoint).actionRoutine(0xfc8540)
	/home/suda/gopath/src/github.com/osrg/namazu/nmz/endpoint/local/localendpoint.go:71 +0x3c8
created by github.com/osrg/namazu/nmz/endpoint/local.(*LocalEndpoint).Start
	/home/suda/gopath/src/github.com/osrg/namazu/nmz/endpoint/local/localendpoint.go:101 +0x170

goroutine 20 [select]:
github.com/osrg/namazu/nmz/util/mockorchestrator.(*MockOrchestrator).routine(0xc821188080)
	/home/suda/gopath/src/github.com/osrg/namazu/nmz/util/mockorchestrator/mockorchestrator.go:81 +0x193
created by github.com/osrg/namazu/nmz/util/mockorchestrator.(*MockOrchestrator).Start
	/home/suda/gopath/src/github.com/osrg/namazu/nmz/util/mockorchestrator/mockorchestrator.go:99 +0x35

goroutine 21 [runnable]:
testing.decorate(0xc8211d6000, 0x83, 0x0, 0x0)
	/home/suda/go/src/testing/testing.go:238 +0x1da
testing.(*common).log(0xc8200ac5a0, 0xc8211d6000, 0x83)
	/home/suda/go/src/testing/testing.go:353 +0x8e
testing.(*common).Logf(0xc8200ac5a0, 0xa77730, 0xb, 0xc821183e18, 0x2, 0x2)
	/home/suda/go/src/testing/testing.go:366 +0x75
_/home/suda/WORK/namazu/nmz/inspector/ethernet.testHookSwitchInspector(0xc8200ac5a0, 0xa)
	/home/suda/WORK/namazu/nmz/inspector/ethernet/ethernet_test.go:90 +0x646
_/home/suda/WORK/namazu/nmz/inspector/ethernet.TestHookSwitchInspector_10(0xc8200ac5a0)
	/home/suda/WORK/namazu/nmz/inspector/ethernet/ethernet_test.go:65 +0x2a
testing.tRunner(0xc8200ac5a0, 0xfaa8e0)
	/home/suda/go/src/testing/testing.go:473 +0x98
created by testing.RunTests
	/home/suda/go/src/testing/testing.go:582 +0x892

goroutine 22 [runnable]:
reflect.typedmemmove(0x89db40, 0xc8211a6020, 0xc820019e00)
	/home/suda/go/src/runtime/mbarrier.go:201
reflect.packEface(0x89db40, 0xc820019e00, 0x198, 0x0, 0x0)
	/home/suda/go/src/reflect/value.go:113 +0x120
reflect.valueInterface(0x89db40, 0xc820019e00, 0x198, 0x1, 0x0, 0x0)
	/home/suda/go/src/reflect/value.go:938 +0x1ec
reflect.Value.Interface(0x89db40, 0xc820019e00, 0x198, 0x0, 0x0)
	/home/suda/go/src/reflect/value.go:908 +0x48
fmt.(*pp).printValue(0xc8211ba000, 0x89db40, 0xc820019e00, 0x198, 0x76, 0x2, 0x198)
	/home/suda/go/src/fmt/print.go:842 +0x372
fmt.(*pp).printReflectValue(0xc8211ba000, 0xa12c00, 0xc820019e00, 0x199, 0xc800000076, 0x1, 0x0)
	/home/suda/go/src/fmt/print.go:932 +0x3b79
fmt.(*pp).printValue(0xc8211ba000, 0xa12c00, 0xc820019e00, 0x199, 0x76, 0x1, 0x20)
	/home/suda/go/src/fmt/print.go:848 +0x440
fmt.(*pp).printReflectValue(0xc8211ba000, 0x9ea9a0, 0xc820019e00, 0x16, 0x76, 0x0, 0x0)
	/home/suda/go/src/fmt/print.go:1009 +0x351e
fmt.(*pp).printArg(0xc8211ba000, 0x9ea9a0, 0xc820019e00, 0x76, 0x0, 0x0)
	/home/suda/go/src/fmt/print.go:810 +0x540
fmt.(*pp).doPrintf(0xc8211ba000, 0xb0dcc0, 0x23, 0xc8211a6000, 0x1, 0x1)
	/home/suda/go/src/fmt/print.go:1238 +0x1dcd
fmt.Sprintf(0xb0dcc0, 0x23, 0xc8211a6000, 0x1, 0x1, 0x0, 0x0)
	/home/suda/go/src/fmt/print.go:203 +0x6f
github.com/cihub/seelog.(*logFormattedMessage).String(0xc8211aa000, 0x0, 0x0)
	/home/suda/gopath/src/github.com/cihub/seelog/logger.go:369 +0x58
github.com/cihub/seelog.(*commonLogger).processLogMsg(0xc8200aa300, 0x1, 0x7f0abf0f47c0, 0xc8211aa000, 0x7f0abf0f47e8, 0xc8211b8000)
	/home/suda/gopath/src/github.com/cihub/seelog/logger.go:312 +0x8e
github.com/cihub/seelog.(*syncLogger).innerLog(0xc8200aa300, 0x1, 0x7f0abf0f47e8, 0xc8211b8000, 0x7f0abf0f47c0, 0xc8211aa000)
	/home/suda/gopath/src/github.com/cihub/seelog/behavior_synclogger.go:51 +0x59
github.com/cihub/seelog.(*commonLogger).log(0xc8200aa300, 0x1, 0x7f0abf0f47c0, 0xc8211aa000, 0x3)
	/home/suda/gopath/src/github.com/cihub/seelog/logger.go:302 +0x181
github.com/cihub/seelog.(*commonLogger).debugWithCallDepth(0xc8200aa300, 0x3, 0x7f0abf0f47c0, 0xc8211aa000)
	/home/suda/gopath/src/github.com/cihub/seelog/logger.go:234 +0x44
github.com/cihub/seelog.Debugf(0xb0dcc0, 0x23, 0xc8211a6000, 0x1, 0x1)
	/home/suda/gopath/src/github.com/cihub/seelog/log.go:210 +0x13f
_/home/suda/WORK/namazu/nmz/inspector/ethernet.(*HookSwitchInspector).Serve(0xc820019e00, 0x0, 0x0)
	/home/suda/WORK/namazu/nmz/inspector/ethernet/ethernet_hookswitch.go:57 +0xee
_/home/suda/WORK/namazu/nmz/inspector/ethernet.testHookSwitchInspector.func1(0xc820019e00)
	/home/suda/WORK/namazu/nmz/inspector/ethernet/ethernet_test.go:83 +0x21
created by _/home/suda/WORK/namazu/nmz/inspector/ethernet.testHookSwitchInspector
	/home/suda/WORK/namazu/nmz/inspector/ethernet/ethernet_test.go:84 +0x3f7

goroutine 23 [select]:
github.com/vaughan0/go-zmq.(*Channels).processOutgoing(0xc8211a4060)
	/home/suda/gopath/src/github.com/vaughan0/go-zmq/channels.go:72 +0x31b
created by github.com/vaughan0/go-zmq.(*Socket).ChannelsBuffer
	/home/suda/gopath/src/github.com/vaughan0/go-zmq/channels.go:37 +0x2af
exit status 2
FAIL	_/home/suda/WORK/namazu/nmz/inspector/ethernet	0.100s
```

**Comment by AkihiroSuda** [comment]
The failure seems unrelated to renaming, perhaps because I recently upgraded my Ubuntu 16.04 env to 16.10.
I'll open another issue

**Comment by AkihiroSuda** [comment]
Tested following things:
- `./build` works (with a fresh GOPATH)
- `go test ./...` works (ditto)
- `nmz --help` works
- `nmz container run -it --rm ubuntu bash` works
- `./example/zk-found-2212.nfqhook` is reproducible
- `./example/zk-repro-2080.nfqhook` is reproducible
- `./example/yarn/4301-reproduce` is reproducible

Environment: Ubuntu 16.04 amd64
I didn't test the DinD image yet.

I'll merge after adding the logo.

**Pull request merged**
